### ISSUE TITLE
Timeline shows nothing when a GNUsocial status is "retoot"

### ISSUE THREAD

**Issue by dalmemail** [AzetJP/mastodon-timeline-widget#2]
As the title says when the Mastodon account which is displayed by the timeline widget "retoots" an status from a GNUsocial user (as you probably know the GNU social network federates with Mastodon) the widget looks empty. Please fix it :-)

**Comment by AzetJP** [comment]
Hello,
Thank you very much for your report.
We are very sorry for the so long delay in our answer.
We finally had some time to work on it today.
We also handled boosts more properly to reflect more the UI in mastodon.
